version: '3'
services:
  bot:
    build: .
    container_name: gemini
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
  redis:
    container_name: my_redis_container
    image: redis
